version: '3.5'

volumes:
  jenkins-data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql_data:

networks:
  docker-jenkins-sonarqube:
    name: docker-jenkins-sonarqube

services:
  jenkins:
    image: jenkinsci/blueocean
    networks:
    - docker-jenkins-sonarqube
    user: root
    ports:
    - "8080:8080"
    volumes:
    - jenkins-data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
  sonar:
    image: sonarqube:7.7-community
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    networks:
    - docker-jenkins-sonarqube
    volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    links:
    - db
    ports:
    - "9000:9000"
    - "9092:9092"
  db:
    image: postgres
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    networks:
    - docker-jenkins-sonarqube
    volumes:
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
    - postgresql_data:/var/lib/postgresql/data